spring:
  datasource:
    url: jdbc:mysql://dolbomi-database.c3fgscikrkef.ap-northeast-2.rds.amazonaws.com:3306/Dolbomi?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: young123
  redis:
    session:
      host: localhost
      port: 6379

mybatis:
  type-aliases-package: com.example.dolbomi.*.domain
  mapper-locations: mybatis/mapper/**/*.xml