spring:
  datasource:
    url: jdbc:mysql://52.78.83.195:3306/Dolbomi?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: woosung
    password:

mybatis:
  type-aliases-package: com.example.dolbomi.*.domain
  mapper-locations: mybatis/mapper/**/*.xml